<snippet>
	<content><![CDATA[
func Test${1:FuncName}(t *testing.T) {
	t.Parallel()

	type args struct {
		content string
	}

	cases := map[string]struct {
		args      args
		want      bool
		wantErr   error
	}{
		"simple": {
			args{
				content: "test",
			},
			false,
			errors.New("testing error"),
		},
	}

	for intention, testCase := range cases {
		intention := intention
		testCase := testCase

		t.Run(intention, func(t *testing.T) {
			t.Parallel()

			got, gotErr := ${1:FuncName}(testCase.args.content)

			failed := false

			switch {
			case
				testCase.wantErr == nil && gotErr != nil,
				testCase.wantErr != nil && gotErr == nil,
				testCase.wantErr != nil && !strings.Contains(gotErr.Error(), testCase.wantErr.Error()),
				got != testCase.want:
				failed = true
			}

			if failed {
				t.Errorf("${1:FuncName}() = (%t, `%s`), want (%t, `%s`)", got, gotErr, testCase.want, testCase.wantErr)
			}
		})
	}
}

]]></content>
	<tabTrigger>gte</tabTrigger>
	<scope>source.go</scope>
	<description>Golang Test with Error</description>
</snippet>
